#!/bin/bash

# compile new tint2 from git

# dependecies
sudo apt install -y libcairo2-dev libpango1.0-dev libglib2.0-dev libimlib2-dev libgtk2.0-dev libxinerama-dev libx11-dev libxdamage-dev libxcomposite-dev libxrender-dev libxrandr-dev librsvg2-dev libstartup-notification0-dev
sudo apt install -y cmake checkinstall

cd ~/source/ || exit

git clone https://gitlab.com/o9000/tint2.git
cd tint2 || exit
# checkout if you want specific version, see page
mkdir build 
cd build || exit

cmake ..
make

# make a soft link in ~/bin, at next login the new tint2 will be started

newtint2="~/source/tint2/build/tint2"
if [ -f $newtint2 ]; then
   ln -s ~/source/tint2/build/tint2 ~/bin/tint2
else
   echo "something went wrong."
fi


