#!/bin/bash

# run with sudo

apt install -y $(cat atom.list) || exit
apt install -y $(cat base.list)
apt install -y --no-install-recommends $(cat baseNoInstallRec.list)
#apt install -y $(cat extra.list)

# wbar
sudo rm /etc/xdg/autostart/wbar.desktop # start wbar in ob autostart
